### ISSUE TITLE
Consider moving Options under Sub Heading

### ISSUE THREAD

**Issue by salcode** [chrispian/draft-post-disclaimer#2]
I'd consider moving the options moved under `Settings` in the menu.

![Screen Shot 2020-02-28 at 15 17 13 ](https://user-images.githubusercontent.com/5194588/75584298-6f000a80-5a3d-11ea-9985-997671686132.png)

Along with this, you might want to put a link from the Plugin page directly to the settings. I really like when plugins have this. This code in your main plugin file adds it. I've not thought about a good OOP way to add this

```
add_filter('plugin_action_links_'.plugin_basename(__FILE__), 'salcode_add_plugin_page_settings_link');
function salcode_add_plugin_page_settings_link( $links ) {
	$links[] = '<a href="' .
		admin_url( 'options-general.php?page=my-plugin' ) .
		'">' . __('Settings') . '</a>';
	return $links;
}
```

Code from https://salferrarello.com/wordpress-plugin-add-settings-link/

**Comment by chrispian** [comment]
Good idea! I prefer both of these things too. Adding to my to do list.

**Comment by chrispian** [comment]
Thanks again, both of these have been added in!
