### ISSUE TITLE
Eliminate static method calls src/Disclaimer.php

### ISSUE THREAD

**Issue by salcode** [chrispian/draft-post-disclaimer#3]
Currently, you don't have any [static methods](https://www.php.net/manual/en/language.oop5.static.php) in [src/Disclaimer.php](https://github.com/chrispian/draft-post-disclaimer/blob/d2173074530d86d2adfae939ba1ed147d69d90e7/src/Disclaimer.php), therefore we don't want to call any of the methods with the form (e.g. we don't want to call `Disclaimer::maybe_display_notice()`).

Instead we want to call the methods with `$this->maybe_display_notice()`.

**Comment by chrispian** [comment]
Good catch! Fixed in #6
